version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: music_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - music_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: music_library
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - music_network

networks:
  music_network:
    driver: bridge