version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=music_library
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: music_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  default:
    name: music_library_network